inherit_from: ".rubocop.yml"

plugins:
  - rubocop-md

AllCops:
  Include:
    - '**/*.md'

Lint/Void:
  Exclude:
    - '**/*.md'

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
    - '**/*.md'
